### PR TITLE
Overall teacher rating

### LINKED ISSUE #1: As a user, I can view ratings for a specific teacher (frontend)
Acceptance Criteria:
- [x] Results should show only for the teacher specified
- [x] Overall rating for a teacher should be visible in both numerical and graph format
- [x] Should generally follow the previously specified design

### PR DESCRIPTION
**Pull request by sophkirchner**
formatting is trash, but rating aggregation should (might) work (completely untested) (probably fine)

### CODE REVIEW

**Comment by sophkirchner** [comment]
Note: Please do not merge until we test this with the data seed

**Review by malcolm5858 — COMMENTED** [review]
Looks good

**Comment by sophkirchner** [comment]
> 
> 
> Looks good

lmao no it doesn't
image

**Review by malcolm5858 — APPROVED** [review]
Looks good

**Pull request merged**
